### ISSUE TITLE
Server not working after loading script when no client is connected

### ISSUE THREAD

**Issue by FTSMO** [MonsterDruide1/smo-practice-server#2]
After accidentally loading a script when no client is connected, this error comes up and you can't type anything into the server.

Exception in thread "main" java.lang.IllegalStateException: No client currently connected
        at server.Server.sendData(Server.java:73)
        at server.Server.sendPackets(Server.java:64)
        at server.Main.consoleLoop(Main.java:63)
        at server.Main.startLoop(Main.java:50)
        at server.Main.bootup(Main.java:38)
        at server.Main.main(Main.java:31)

**Comment by MonsterDruide1** [comment]
That exception is expected (well, there is indeed no client connected), but it shouldn't get a full crash afterwards. I'll investigate.

**Comment by MonsterDruide1** [comment]
I just published a new release, `v1.0.2`, which has this issue fixed. Please tell me if further issues arise with this.
